[package]
name = "otf-app"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.20.1", features = ["wgpu"] }
otf-kernels = { path = "../otf-kernels" }
rerun = { version = "0.29.2", features = ["demo"] }
itertools = "0.14"
rand = "0.8"
